import sys
import os
import re

# Tambahkan direktori parent ke sys.path
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from my_app.app import create_app
from my_app.extensions import db
from my_app.models import Student

def clean_name(raw_name):
    # Hapus angka di depan dan L/P di belakang
    # Contoh: "1Aaliyah Nazwa DefindaP" -> "Aaliyah Nazwa Definda"
    # Regex: Hapus digit awal, hapus spasi/L/P di akhir
    name = re.sub(r'^\d+', '', raw_name) # Hapus angka depan
    name = re.sub(r'[LP]$', '', name.strip()) # Hapus L/P di akhir (jika nempel)
    return name.strip()

def seed_students_manual():
    app = create_app()
    
    # Data Siswa dari input Anda (Sudah dirapikan)
    students_data = [
        # --- KELAS 9A ---
        {'kelas': '9A', 'nama': 'Aaliyah Nazwa Definda'},
        {'kelas': '9A', 'nama': 'Ailyka Najmahira Kinanti'},
        {'kelas': '9A', 'nama': 'Akbar Adi Wardhana'},
        {'kelas': '9A', 'nama': 'Ameera Hafeeza Ilhami'},
        {'kelas': '9A', 'nama': 'Annisa Salsabila Handaru'},
        {'kelas': '9A', 'nama': 'Arkha Irsyad Putratian'},
        {'kelas': '9A', 'nama': 'Artisha Putri Garibaldi'},
        {'kelas': '9A', 'nama': 'Bassam Azis Ambadar'},
        {'kelas': '9A', 'nama': 'Beryl Radi Tirto'},
        {'kelas': '9A', 'nama': 'Btari Arum Pratiwi'},
        {'kelas': '9A', 'nama': 'Evan Nararya Adhiloka'},
        {'kelas': '9A', 'nama': 'Fagan Kaiva Abipraya'},
        {'kelas': '9A', 'nama': 'Fattah Raziq Wicaksono'},
        {'kelas': '9A', 'nama': 'Felovy Celine Afradinka'},
        {'kelas': '9A', 'nama': 'Ganesh Maiman Kusumo'},
        {'kelas': '9A', 'nama': 'Gayatri Irdina Iskandar'},
        {'kelas': '9A', 'nama': 'Ghifary Gibran Farizki Hasyim'},
        {'kelas': '9A', 'nama': 'Isabelle Ramadhani Lylu'},
        {'kelas': '9A', 'nama': 'Kayana Allica Soegomo'},
        {'kelas': '9A', 'nama': 'Keef Alaric Seta Delindra'},
        {'kelas': '9A', 'nama': 'Khansaa Luigina Latif'},
        {'kelas': '9A', 'nama': 'Muhammad Ammardhiya Mulya'},
        {'kelas': '9A', 'nama': 'Muhammad Kenzie Surya Haryanto'},
        {'kelas': '9A', 'nama': 'Naureen Nadira Nazrana'},
        {'kelas': '9A', 'nama': 'Nayla Fayza Kusuma'},
        {'kelas': '9A', 'nama': 'Pavita Azalia Priambudi'},
        {'kelas': '9A', 'nama': 'Queenza Raissa Tiarta Nazifa'},
        {'kelas': '9A', 'nama': 'Raden Baskara Cakrawinata'},
        {'kelas': '9A', 'nama': 'Revanullah'},
        {'kelas': '9A', 'nama': 'Safa Azalia Farras Iasya'},
        {'kelas': '9A', 'nama': 'Salsabilla Ayu Handoko'},
        {'kelas': '9A', 'nama': 'Shakira Awwa Benazir'},
        {'kelas': '9A', 'nama': 'Shazia Queencettalita Mizakha'},
        {'kelas': '9A', 'nama': 'Syafina Nur Layla'},
        {'kelas': '9A', 'nama': 'Wiliko Victoriafirli Wijaya'},

        # --- KELAS 9B ---
        {'kelas': '9B', 'nama': 'Alif Ahmad Al Abqory'},
        {'kelas': '9B', 'nama': 'Ammara Davina Erissa'},
        {'kelas': '9B', 'nama': 'Andi Dzakiyah Az Zahra'},
        {'kelas': '9B', 'nama': 'Andra Sadewa Wahyudi'},
        {'kelas': '9B', 'nama': 'Anindya Nisrina Wahyuningtyas'},
        {'kelas': '9B', 'nama': 'Anisa Dwi Safitri Azzahra'},
        {'kelas': '9B', 'nama': 'Athar Malaika Aryasatya'},
        {'kelas': '9B', 'nama': 'Azima Zhafirah Abrar'},
        {'kelas': '9B', 'nama': 'Azka Zain Nafilandra'},
        {'kelas': '9B', 'nama': 'Eruzaka Khalif Harseno'},
        {'kelas': '9B', 'nama': 'Fernando Raka Murtias Edi'},
        {'kelas': '9B', 'nama': 'Irham Dante Rudyana'},
        {'kelas': '9B', 'nama': 'Kaelie Alinaiya Almeera Rahman'},
        {'kelas': '9B', 'nama': 'Keisha Putri Sagita'},
        {'kelas': '9B', 'nama': 'Khanza Khalifa Ramadhani'},
        {'kelas': '9B', 'nama': 'Khanzia Almahyra Ghassani'},
        {'kelas': '9B', 'nama': 'Kimora Azzalea Gradista'},
        {'kelas': '9B', 'nama': 'Kinarhayu Nayla Rahma'},
        {'kelas': '9B', 'nama': 'Lareina Elvina Shahia'},
        {'kelas': '9B', 'nama': 'Mars Tyaga Harmadwijaya'},
        {'kelas': '9B', 'nama': 'Muhammad Al Maliq Athallah'},
        {'kelas': '9B', 'nama': 'Muhammad Alfath Irvani'},
        {'kelas': '9B', 'nama': 'Muhammad Bidara Arkana'},
        {'kelas': '9B', 'nama': 'Muhammad Dzaky Rachman'},
        {'kelas': '9B', 'nama': 'Muhammad Fidel Panedya'},
        {'kelas': '9B', 'nama': 'Muhammad Rif\'at Putra Rianto'},
        {'kelas': '9B', 'nama': 'Muhammad Zidni Irawan'},
        {'kelas': '9B', 'nama': 'Nadhifa Qiana Anaya'},
        {'kelas': '9B', 'nama': 'Nouval Adam Candra'},
        {'kelas': '9B', 'nama': 'Owais Zeidan Rizwan'},
        {'kelas': '9B', 'nama': 'Raditya Wahyu Febriansyah'},
        {'kelas': '9B', 'nama': 'Rafa Dyandra Wibowo'},
        {'kelas': '9B', 'nama': 'Rafif Naufal Yudhanto'},
        {'kelas': '9B', 'nama': 'Rizky Alfriandri'},
        {'kelas': '9B', 'nama': 'Rosanna Adhalia Barhan'},
        {'kelas': '9B', 'nama': 'Zaviero Azka Ariansha'},

        # --- KELAS 9C ---
        {'kelas': '9C', 'nama': 'Afgan Nakula Wahyudi'},
        {'kelas': '9C', 'nama': 'Alfathur Nararya Jatmiko'},
        {'kelas': '9C', 'nama': 'Alkifaah Firendi Assajad'},
        {'kelas': '9C', 'nama': 'Ariqa Fathia Rachman'},
        {'kelas': '9C', 'nama': 'Azka Putra Aruna'},
        {'kelas': '9C', 'nama': 'Damar Bagus Rafassya'},
        {'kelas': '9C', 'nama': 'Daniswara Naja Anindya'},
        {'kelas': '9C', 'nama': 'Darrell Akhtareva Harsya'},
        {'kelas': '9C', 'nama': 'Davina Putri'},
        {'kelas': '9C', 'nama': 'Febrian Rizky Prasetya'},
        {'kelas': '9C', 'nama': 'Gavin Rafano Hakim'},
        {'kelas': '9C', 'nama': 'Ghazi Arsyiqa Fajrig'},
        {'kelas': '9C', 'nama': 'Hikoshi Ramardi Ridwan'},
        {'kelas': '9C', 'nama': 'Hugo Aozora Maulana'},
        {'kelas': '9C', 'nama': 'Kayla Adiva Rahman'},
        {'kelas': '9C', 'nama': 'Khalifa Zuhayr Noor'},
        {'kelas': '9C', 'nama': 'Kinsey Abhivara Catrabumi'},
        {'kelas': '9C', 'nama': 'Malvie Sheza Chaerul'},
        {'kelas': '9C', 'nama': 'Mohamad Kemal Azis Nugroho'},
        {'kelas': '9C', 'nama': 'Muhammad Al Farisi Fahed'},
        {'kelas': '9C', 'nama': 'Muhammad Arya Danurwenda'},
        {'kelas': '9C', 'nama': 'Muhammad Hudan Adzikri'},
        {'kelas': '9C', 'nama': 'Muhammad Imam Rahmadi Wiryotaruno'},
        {'kelas': '9C', 'nama': 'Muhammad Kaykaus Xavier Muzhaffar'},
        {'kelas': '9C', 'nama': 'Narendra Abimanyu Budiono'},
        {'kelas': '9C', 'nama': 'Nur Dzakiya Putri Azzahra'},
        {'kelas': '9C', 'nama': 'Pandu Anindito Nasuha'},
        {'kelas': '9C', 'nama': 'Princess Janeeta Syalabia'},
        {'kelas': '9C', 'nama': 'Revanda Omar Fathani'},
        {'kelas': '9C', 'nama': 'Setya Aira Pratiwi'},
        {'kelas': '9C', 'nama': 'Siti Dewi Kumala'},
        {'kelas': '9C', 'nama': 'Tanisha Harharah'},
        {'kelas': '9C', 'nama': 'Umar Muhsin'},
        {'kelas': '9C', 'nama': 'Vajra Islami Pasha'},
        {'kelas': '9C', 'nama': 'Yura Anindita'},

        # --- KELAS 9D ---
        {'kelas': '9D', 'nama': 'Abilla Tristan Arya Andiry'},
        {'kelas': '9D', 'nama': 'Ahmad Emir Faza'},
        {'kelas': '9D', 'nama': 'Aisyah Sayyidatul Aulia'},
        {'kelas': '9D', 'nama': 'Alya Kania Fadli'},
        {'kelas': '9D', 'nama': 'Alzena Safa Anindita'},
        {'kelas': '9D', 'nama': 'Ariffa Rahman'},
        {'kelas': '9D', 'nama': 'Ayra Fitri Fakhrun Nisa'},
        {'kelas': '9D', 'nama': 'Azzara Qiandra Mahesti'},
        {'kelas': '9D', 'nama': 'Bima Rabbani Alvaro Sidharta'},
        {'kelas': '9D', 'nama': 'Chantika Yasmin Humaira'},
        {'kelas': '9D', 'nama': 'Fabio Alvarano Vaditya'},
        {'kelas': '9D', 'nama': 'Fadhlan Aufa Rahman'},
        {'kelas': '9D', 'nama': 'Fadhlan Azzam Atmajah'},
        {'kelas': '9D', 'nama': 'Fahira Ramadhani'},
        {'kelas': '9D', 'nama': 'Farhan Pramudya Wibowo'},
        {'kelas': '9D', 'nama': 'Fauzan Khairiy Ramdani'},
        {'kelas': '9D', 'nama': 'Febriansyah Indra Setiawan'},
        {'kelas': '9D', 'nama': 'Ghaisan Athar Styawan'},
        {'kelas': '9D', 'nama': 'Gieputra Pierka Nussy'},
        {'kelas': '9D', 'nama': 'Kayla Puan Asyarani'},
        {'kelas': '9D', 'nama': 'Makaela Kalin Jelita'},
        {'kelas': '9D', 'nama': 'Muhamad Izzatus Santri Bagus Harun'},
        {'kelas': '9D', 'nama': 'Muhammad Benzema Harmoko'},
        {'kelas': '9D', 'nama': 'Muhammad Emirsyah Alvaro'},
        {'kelas': '9D', 'nama': 'Muhammad Rai Padawkas'},
        {'kelas': '9D', 'nama': 'Nada Aisyah Azzahra'},
        {'kelas': '9D', 'nama': 'Naila Rafa Andini'},
        {'kelas': '9D', 'nama': 'Prayata Alif Rivsaga'},
        {'kelas': '9D', 'nama': 'Rafif Humam Safian'},
        {'kelas': '9D', 'nama': 'Raihan Kennard Raffasyah'},
        {'kelas': '9D', 'nama': 'Raina Arif Bisyir'},
        {'kelas': '9D', 'nama': 'Raisa Malika Ghania'},
        {'kelas': '9D', 'nama': 'Ramadhan Argie Dzaki Sasomo'},
        {'kelas': '9D', 'nama': 'Rayhan Ramadhan Wahyudi'},
        {'kelas': '9D', 'nama': 'Shafia Wahyu Dwiwarni'},
        {'kelas': '9D', 'nama': 'Zavier Aidan'},

        # --- KELAS 8A ---
        {'kelas': '8A', 'nama': 'Aisha Zerina Alifah'},
        {'kelas': '8A', 'nama': 'Akhmad Syamilov Syahidan Ushain'},
        {'kelas': '8A', 'nama': 'Alanis Saqilah Hendrata'},
        {'kelas': '8A', 'nama': 'Ariq Ahmad Dwi Andhika'},
        {'kelas': '8A', 'nama': 'Bagus Pratama Habibi'},
        {'kelas': '8A', 'nama': 'Callista Naeisha Sutisna'},
        {'kelas': '8A', 'nama': 'Daffy Omar Ayman'},
        {'kelas': '8A', 'nama': 'Fadel Malikunusa Anthonie'},
        {'kelas': '8A', 'nama': 'Fadhil Azka Ramadhan'},
        {'kelas': '8A', 'nama': 'Fadisya Neila Zahra'},
        {'kelas': '8A', 'nama': 'Ganes Azima Anwar'},
        {'kelas': '8A', 'nama': 'Hafiz Rafi Rabbani'},
        {'kelas': '8A', 'nama': 'Janeeta Aqilah Dhistira'},
        {'kelas': '8A', 'nama': 'Jinan Raudhah Anggana'},
        {'kelas': '8A', 'nama': 'Kamaniya Aurora Hariandi'},
        {'kelas': '8A', 'nama': 'Kamiliya Jahra'},
        {'kelas': '8A', 'nama': 'Karim Alexandria Rahula Widdyantoro'},
        {'kelas': '8A', 'nama': 'Kayla Zhafirah Saraswati'},
        {'kelas': '8A', 'nama': 'Melody Kymi Aisyahra'},
        {'kelas': '8A', 'nama': 'Muhammad Agha Arkana Binsar'},
        {'kelas': '8A', 'nama': 'Muhammad Azmi Ramadhan'},
        {'kelas': '8A', 'nama': 'Muhammad Figo Firdaus'},
        {'kelas': '8A', 'nama': 'Muhammad Hanif Abdurrahman'},
        {'kelas': '8A', 'nama': 'Muhammad Jalaluddin Adz Dzikra'},
        {'kelas': '8A', 'nama': 'Muhammad Mirza Athaya'},
        {'kelas': '8A', 'nama': 'Muhammad Rafka Faeyza'},
        {'kelas': '8A', 'nama': 'Muhammad Rafli Aliandra'},
        {'kelas': '8A', 'nama': 'Najla Ramadhani Assaury'},
        {'kelas': '8A', 'nama': 'Nasywah Aulia Putri'},
        {'kelas': '8A', 'nama': 'Nayla Ufaira Revaniputri'},
        {'kelas': '8A', 'nama': 'Niallinka Aquene Athaya'},
        {'kelas': '8A', 'nama': 'Pratama Adi Wijaya'},
        {'kelas': '8A', 'nama': 'Reeyasa Mulansha'},
        {'kelas': '8A', 'nama': 'Renata Adelia Hamka'},
        {'kelas': '8A', 'nama': 'Sakhiya Zahra Intan Medina'},
        {'kelas': '8A', 'nama': 'Zieputri Tiasrylisha Nussy'},

        # --- KELAS 8B ---
        {'kelas': '8B', 'nama': 'Agnalya Quinshefa'},
        {'kelas': '8B', 'nama': 'Ahmad Kurnia Febrian'},
        {'kelas': '8B', 'nama': 'Almyra Adinda Arioputri'},
        {'kelas': '8B', 'nama': 'Anggraeni Putri Wibowo'},
        {'kelas': '8B', 'nama': 'Anindya Dalisa Padmarini'},
        {'kelas': '8B', 'nama': 'Arfa Revaldi Abdillah'},
        {'kelas': '8B', 'nama': 'Arkananta Fathiin Kashafa'},
        {'kelas': '8B', 'nama': 'Arlita Mahira Siswitono'},
        {'kelas': '8B', 'nama': 'Aureen Namalo Marina'},
        {'kelas': '8B', 'nama': 'Berwyn Azka Ramadhan'},
        {'kelas': '8B', 'nama': 'Felicia Putri Wicaksono'},
        {'kelas': '8B', 'nama': 'Gantari Laksita Dewi'},
        {'kelas': '8B', 'nama': 'Haikal Putra Pradana'},
        {'kelas': '8B', 'nama': 'Kanaya Anindita Putri'},
        {'kelas': '8B', 'nama': 'Keandra Shidqi Alkautsar'},
        {'kelas': '8B', 'nama': 'Kenshin Hamami Abdullah'},
        {'kelas': '8B', 'nama': 'Khansa Alfany Sierra'},
        {'kelas': '8B', 'nama': 'Khayyira Adiva Zain'},
        {'kelas': '8B', 'nama': 'Muhammad Adi Koesrahardian'},
        {'kelas': '8B', 'nama': 'Muhammad Damas Alishati Batubara'},
        {'kelas': '8B', 'nama': 'Muhammad Faiq Izyanhasan'},
        {'kelas': '8B', 'nama': 'Muhammad Farhan Fikry Aulia'},
        {'kelas': '8B', 'nama': 'Muhammad Rizky Alkhawarizmy Shiddiq'},
        {'kelas': '8B', 'nama': 'Mumtaz Ghani El Aqiel'},
        {'kelas': '8B', 'nama': 'Nabila Raisha Ayu'},
        {'kelas': '8B', 'nama': 'Nadia Ariadne Tomiarfi'},
        {'kelas': '8B', 'nama': 'Naychinta Zeevandha Suciadi'},
        {'kelas': '8B', 'nama': 'Nindita Widya Pangesthi'},
        {'kelas': '8B', 'nama': 'Ophelia Annissa Kusumawardhani'},
        {'kelas': '8B', 'nama': 'Panji Raksa Ramadhan'},
        {'kelas': '8B', 'nama': 'Pradipta Abdillah Priambudi'},
        {'kelas': '8B', 'nama': 'Rasya Ardianto Pratama'},
        {'kelas': '8B', 'nama': 'Rasya Noer Tsaqif'},
        {'kelas': '8B', 'nama': 'Rayyandra Videllio Atharrayhan Suteja'},
        {'kelas': '8B', 'nama': 'Rihanna Angelica Iskandar'},
        {'kelas': '8B', 'nama': 'Syaima Hasna Alliya Fausi'},

        # --- KELAS 8C ---
        {'kelas': '8C', 'nama': 'Adrista Zulkarnain'},
        {'kelas': '8C', 'nama': 'Arya Bagaskara Satria Perkasa'},
        {'kelas': '8C', 'nama': 'Bimasakti Dhia Ahza'},
        {'kelas': '8C', 'nama': 'Damar Hasbi Alfarizqi'},
        {'kelas': '8C', 'nama': 'Danish Ahza Putra Ardias'},
        {'kelas': '8C', 'nama': 'Ganesa Faiz Jibran'},
        {'kelas': '8C', 'nama': 'Gheana Ghassani Nugeroho'},
        {'kelas': '8C', 'nama': 'Hafid Athallah Keynantara'},
        {'kelas': '8C', 'nama': 'Hamza Ghaisan Noor'},
        {'kelas': '8C', 'nama': 'Inara Ayasovia Pratama'},
        {'kelas': '8C', 'nama': 'Jasmine Queenyla Septiawan'},
        {'kelas': '8C', 'nama': 'Jihan Larisa Putri'},
        {'kelas': '8C', 'nama': 'Keiro Muhammad Arjuna Hario Prabowo'},
        {'kelas': '8C', 'nama': 'Kenzie Nararya Ari Panggung'},
        {'kelas': '8C', 'nama': 'Kioko Elvaretta Jocasta'},
        {'kelas': '8C', 'nama': 'Lilo Prawira'},
        {'kelas': '8C', 'nama': 'Mikaila Syarifah Hudi'},
        {'kelas': '8C', 'nama': 'Muhammad Faeyza Daffa Dyandra'},
        {'kelas': '8C', 'nama': 'Muhammad Raffasya Fauzi'},
        {'kelas': '8C', 'nama': 'Nadira Githa Suharnis'},
        {'kelas': '8C', 'nama': 'Nanne Athaya Fazeela'},
        {'kelas': '8C', 'nama': 'Narendra Dhuha Satriyo'},
        {'kelas': '8C', 'nama': 'Raffiel Prince Angelo'},
        {'kelas': '8C', 'nama': 'Rafif Naufal El Haromaen'},
        {'kelas': '8C', 'nama': 'Sabreen Aliyah Hisam Thalib'},
        {'kelas': '8C', 'nama': 'Shaviya Mazaya Faihana'},
        {'kelas': '8C', 'nama': 'Sultan Yusuf'},
        {'kelas': '8C', 'nama': 'Sylvia Tectonia Azis'},
        {'kelas': '8C', 'nama': 'Tadeo Syafik Ramadhan'},
        {'kelas': '8C', 'nama': 'Tiara Yi Aqilla'},
        {'kelas': '8C', 'nama': 'Valendra Adhyastha Mayza'},
        {'kelas': '8C', 'nama': 'Vania Zahirah Azalia'},
        {'kelas': '8C', 'nama': 'Yota Zhafif Saputra'},
        {'kelas': '8C', 'nama': 'Zenobio Qoidrafif Bastian'},
        {'kelas': '8C', 'nama': 'Zivara Alifa Putri'},

        # --- KELAS 8D ---
        {'kelas': '8D', 'nama': 'Affandi Al Bani'},
        {'kelas': '8D', 'nama': 'Afifah Kamila Putri'},
        {'kelas': '8D', 'nama': 'Aisha Sofia Khairina'},
        {'kelas': '8D', 'nama': 'Aleesya Dania Ghassani'},
        {'kelas': '8D', 'nama': 'Aliya Arundati Az Zahra'},
        {'kelas': '8D', 'nama': 'Arazqa Nafian Ramadhan'},
        {'kelas': '8D', 'nama': 'Aundy Zoya Riqzky Falihah'},
        {'kelas': '8D', 'nama': 'Daniswara Andhika Nugroho'},
        {'kelas': '8D', 'nama': 'Dhafa Wahyu Utama'},
        {'kelas': '8D', 'nama': 'Dimas Fayyadh Hafizhi'},
        {'kelas': '8D', 'nama': 'Dimaz Gentza Aditya'},
        {'kelas': '8D', 'nama': 'Fakhri Syauqi Azzami'},
        {'kelas': '8D', 'nama': 'Fellatisha Irine Kusnandar'},
        {'kelas': '8D', 'nama': 'Galih Ahmad'},
        {'kelas': '8D', 'nama': 'Ibrahim El Hanif'},
        {'kelas': '8D', 'nama': 'Irdinabelle Janeeta Sofia'},
        {'kelas': '8D', 'nama': 'Irham Ramadhan'},
        {'kelas': '8D', 'nama': 'Jazia Qarira Anerez'},
        {'kelas': '8D', 'nama': 'Kurnia Raditya Wibowo'},
        {'kelas': '8D', 'nama': 'Laiqa Farzana'},
        {'kelas': '8D', 'nama': 'Lyo Adira Saffire'},
        {'kelas': '8D', 'nama': 'Mikaila Aisha Aldwinsyah'},
        {'kelas': '8D', 'nama': 'Muhammad Fakhri Arsyad'},
        {'kelas': '8D', 'nama': 'Muhammad Rafassya Alvarezel'},
        {'kelas': '8D', 'nama': 'Nayla Adiva Nisa Kinanti'},
        {'kelas': '8D', 'nama': 'Nazifa Ammara Riandika'},
        {'kelas': '8D', 'nama': 'Quinnissa Sachi Kirana Muliawan'},
        {'kelas': '8D', 'nama': 'Rafif Akhtar Maula Herliano'},
        {'kelas': '8D', 'nama': 'Renzo Tony Narayan'},
        {'kelas': '8D', 'nama': 'Revandra Nararya Alghazi'},
        {'kelas': '8D', 'nama': 'Shaqila Fahira Nadeak'},
        {'kelas': '8D', 'nama': 'Shora Salsabila Rahadhian'},
        {'kelas': '8D', 'nama': 'Triyana Indri Rahayu'},
        {'kelas': '8D', 'nama': 'Tytha Kirana Tunggadewi'},
        {'kelas': '8D', 'nama': 'Zaidan Absyar'},

        # --- KELAS 7A ---
        {'kelas': '7A', 'nama': 'Aditya Wicaksono'},
        {'kelas': '7A', 'nama': 'Afidenaya Myesha Bellvania Kaat'},
        {'kelas': '7A', 'nama': 'Aksa Dewangga Ari Ardhana'},
        {'kelas': '7A', 'nama': 'Alika Amelia Zara'},
        {'kelas': '7A', 'nama': 'Alisya Andina Humaira'},
        {'kelas': '7A', 'nama': 'Almeira Alea Wirawan'},
        {'kelas': '7A', 'nama': 'Bellatrix Queenersia'},
        {'kelas': '7A', 'nama': 'Clearissa Prastiyanto'},
        {'kelas': '7A', 'nama': 'Dafina Fakhira Afan'},
        {'kelas': '7A', 'nama': 'Dyandra Zulaikha Sufi'},
        {'kelas': '7A', 'nama': 'Faristha Savina Azzahra'},
        {'kelas': '7A', 'nama': 'Haikal Aditya Hedin'},
        {'kelas': '7A', 'nama': 'Kanaya Rafifah Gunawan'},
        {'kelas': '7A', 'nama': 'Kannaya Cira Tabina'},
        {'kelas': '7A', 'nama': 'Liefya Lituhayu Qivara'},
        {'kelas': '7A', 'nama': 'Muhammad Kenzo Abyan Fauzi'},
        {'kelas': '7A', 'nama': 'Muhammad Yaser'},
        {'kelas': '7A', 'nama': 'Muhammad Zharif Sandyputra'},
        {'kelas': '7A', 'nama': 'Najwa adrewias az zahra'},
        {'kelas': '7A', 'nama': 'Naoki Kindra Erwin'},
        {'kelas': '7A', 'nama': 'Pradipta Dwi Pambudi'},
        {'kelas': '7A', 'nama': 'Pramesela Helga Dewani'},
        {'kelas': '7A', 'nama': 'Raffadhan Athaya Deandri'},
        {'kelas': '7A', 'nama': 'Raffi Darrell Alvaro'},
        {'kelas': '7A', 'nama': 'Raffiandra Pandji Wibowo'},
        {'kelas': '7A', 'nama': 'Rakeinan Yodha Pratama'},
        {'kelas': '7A', 'nama': 'Rayhana Shabrina Taqiyya'},
        {'kelas': '7A', 'nama': 'Razaidan Raisani Hardhitya'},
        {'kelas': '7A', 'nama': 'Razqa Danish Fakhreza'},
        {'kelas': '7A', 'nama': 'Russell fabian novrico'},
        {'kelas': '7A', 'nama': 'Ryuuki Khaizran Satria'},
        {'kelas': '7A', 'nama': 'Syathir'},
        {'kelas': '7A', 'nama': 'Taneesha Shafwa Kayana D S'},
        {'kelas': '7A', 'nama': 'Zahran Rizki Ramadhan'},
        {'kelas': '7A', 'nama': 'Zia Aqila Putri'},

        # --- KELAS 7B ---
        {'kelas': '7B', 'nama': 'Adella Anindita'},
        {'kelas': '7B', 'nama': 'Akhtar Gibran adhikara'},
        {'kelas': '7B', 'nama': 'Alezhya Tavia Fidita'},
        {'kelas': '7B', 'nama': 'Andres Alfath Maulana'},
        {'kelas': '7B', 'nama': 'Anzu Lee Darmawan'},
        {'kelas': '7B', 'nama': 'Aqeela Dealova Arthur'},
        {'kelas': '7B', 'nama': 'Ardhya Raisha Fahira'},
        {'kelas': '7B', 'nama': 'Arfan Ziqri Sastrawijaya'},
        {'kelas': '7B', 'nama': 'Arrafi Maher Rabbani'},
        {'kelas': '7B', 'nama': 'Aura Latisha Ramadhina'},
        {'kelas': '7B', 'nama': 'Azzura Afief Sungkar'},
        {'kelas': '7B', 'nama': 'Byantara Dalin Naladhipa'},
        {'kelas': '7B', 'nama': 'Evan Athalla Wardhana'},
        {'kelas': '7B', 'nama': 'Fakhriyyah Abidatul Idlal'},
        {'kelas': '7B', 'nama': 'Fikran Azka Kaffah Hardiansyah'},
        {'kelas': '7B', 'nama': 'Hafidz Ghulam Dzakwaan'},
        {'kelas': '7B', 'nama': 'Hana Aira Nasheefa Prasetya'},
        {'kelas': '7B', 'nama': 'Hanif Alvaro Deandro'},
        {'kelas': '7B', 'nama': 'Hugo Safaraz Ali'},
        {'kelas': '7B', 'nama': 'Kafeel Arfalla Santoso'},
        {'kelas': '7B', 'nama': 'Kaleela Azzahra Dwicahya'},
        {'kelas': '7B', 'nama': 'Kayla Azzahra Nursetia Wibowo'},
        {'kelas': '7B', 'nama': 'Kenza Janeeta'},
        {'kelas': '7B', 'nama': 'Ksatria Akmal Zain Adinugroho'},
        {'kelas': '7B', 'nama': 'Malik Avicenna Mahendra Putra'},
        {'kelas': '7B', 'nama': 'Mayesa Aurelia Azeeza'},
        {'kelas': '7B', 'nama': 'Muhammad Fansuri Al Khawarizmi'},
        {'kelas': '7B', 'nama': 'Mutia Amira Davina'},
        {'kelas': '7B', 'nama': 'Pandu Putra Pratama'},
        {'kelas': '7B', 'nama': 'Queenyla Alisha Fakhry'},
        {'kelas': '7B', 'nama': 'Raisa Alifa Rizal'},
        {'kelas': '7B', 'nama': 'Ratu Kaylea Juanito'},
        {'kelas': '7B', 'nama': 'Salsabila Cinta Alfani'},
        {'kelas': '7B', 'nama': 'Satriadji Arya Widura'},
        {'kelas': '7B', 'nama': 'Zafran Ananda Kenji'},
        {'kelas': '7B', 'nama': 'Zaiden AlRasyid Kurniawan'},

        # --- KELAS 7C ---
        {'kelas': '7C', 'nama': 'Abbyan Kenshaka Jodyphati'},
        {'kelas': '7C', 'nama': 'Abdullah'},
        {'kelas': '7C', 'nama': 'Ahmad Hanif Arsyad Arkana'},
        {'kelas': '7C', 'nama': 'Alvina Auliya Shafira'},
        {'kelas': '7C', 'nama': 'Amody Jasinda Sandelova'},
        {'kelas': '7C', 'nama': 'Aqil Nararya'},
        {'kelas': '7C', 'nama': 'Arsa Pradipta Jatikusuma'},
        {'kelas': '7C', 'nama': 'Arya Dzaki Avicenna'},
        {'kelas': '7C', 'nama': 'Ayesa Jauza Afika Putri'},
        {'kelas': '7C', 'nama': 'Bimasena Bayu Pradhaksina'},
        {'kelas': '7C', 'nama': 'Devan Azka Putra Rachman Burhan'},
        {'kelas': '7C', 'nama': 'Farhana Atiqah Faiha'},
        {'kelas': '7C', 'nama': 'Fatimah Azzahra Al Mardiyyah'},
        {'kelas': '7C', 'nama': 'Fayra Zanneta Alesha'},
        {'kelas': '7C', 'nama': 'Friska Wulandari'},
        {'kelas': '7C', 'nama': 'Ghifary Azhar Praditya'},
        {'kelas': '7C', 'nama': 'Hanif Mahdy Ramadhan'},
        {'kelas': '7C', 'nama': 'Ivania Arshyla Dwiputri'},
        {'kelas': '7C', 'nama': 'Kenzou Alzaidan Gradista'},
        {'kelas': '7C', 'nama': 'M. Nurrahman Setyadi'},
        {'kelas': '7C', 'nama': 'Muhammad Aviel Jafisa'},
        {'kelas': '7C', 'nama': 'Muhammad Kenzie Tirta'},
        {'kelas': '7C', 'nama': 'Muhammad Raffif Athalla Dewanto'},
        {'kelas': '7C', 'nama': 'Muhammad Thofainal Ahyar'},
        {'kelas': '7C', 'nama': 'Nadira Andyan Kanzia'},
        {'kelas': '7C', 'nama': 'Nashwa Kamilla Irfani'},
        {'kelas': '7C', 'nama': 'Nizzar Al Hafidz Herlambang'},
        {'kelas': '7C', 'nama': 'Ramadhan Ahmad Wiryawan'},
        {'kelas': '7C', 'nama': 'Razza Sakhi Putra'},
        {'kelas': '7C', 'nama': 'Rizella Calysta Putryanska'},
        {'kelas': '7C', 'nama': 'Sains Kafilla Aalkhawarizmi'},
        {'kelas': '7C', 'nama': 'Thalisa Tunggadewi Priyanto'},
        {'kelas': '7C', 'nama': 'Wildan Zhafran Ahmad'},
        {'kelas': '7C', 'nama': 'Yusri Darmawan Mahardika'},
        {'kelas': '7C', 'nama': 'Zafira Putri Maulana'},
        {'kelas': '7C', 'nama': 'Zaila Helga Janeeta'},

        # --- KELAS 7D ---
        {'kelas': '7D', 'nama': 'Abhie Rasyah Ardinata'},
        {'kelas': '7D', 'nama': 'Adhiza Triarifin'},
        {'kelas': '7D', 'nama': 'Akhmad Bilal Alkhalifi Akhtar'},
        {'kelas': '7D', 'nama': 'Alqiera Mazayya Haris'},
        {'kelas': '7D', 'nama': 'Aqilla Darindra Kirana'},
        {'kelas': '7D', 'nama': 'Ashilla Zhivania'},
        {'kelas': '7D', 'nama': 'Aslam abid giri saputro'},
        {'kelas': '7D', 'nama': 'Delfino Atha Nara Pringgo'},
        {'kelas': '7D', 'nama': 'Dimas Baihaqi'},
        {'kelas': '7D', 'nama': 'Dzydan Anugerah Nuryachya'},
        {'kelas': '7D', 'nama': 'Fakhira Shakila Madjid'},
        {'kelas': '7D', 'nama': 'Gantrazian Fishiyam Kanayufa'},
        {'kelas': '7D', 'nama': 'Haura Insiyah Janeeta'},
        {'kelas': '7D', 'nama': 'Jabril Nawa Al Mujtaba Zaenal'},
        {'kelas': '7D', 'nama': 'Jemmima Syakeella Farizki'},
        {'kelas': '7D', 'nama': 'Kania Putri Ramadhani'},
        {'kelas': '7D', 'nama': 'Kayla Nafisha Misnandi'},
        {'kelas': '7D', 'nama': 'Kenzie Prabaswara Bayone'},
        {'kelas': '7D', 'nama': 'Kynar Almeera Rheamadina'},
        {'kelas': '7D', 'nama': 'Labiq Otham Akhsan'},
        {'kelas': '7D', 'nama': 'Marissa Dealova'},
        {'kelas': '7D', 'nama': 'Muhammad Daniswara Budiman'},
        {'kelas': '7D', 'nama': 'Muhammad Attila Ghifariandra'},
        {'kelas': '7D', 'nama': 'Muhammad Kamil Athaillah'},
        {'kelas': '7D', 'nama': 'Muhammad Pilar Muslimin'},
        {'kelas': '7D', 'nama': 'Muhammad Rigel Ragnala Irawan'},
        {'kelas': '7D', 'nama': 'Muhammad Satria Prayudha Ananto'},
        {'kelas': '7D', 'nama': 'Muhammad Tristan Ramadhan'},
        {'kelas': '7D', 'nama': 'Nadhifah Nur Afizah'},
        {'kelas': '7D', 'nama': 'Rafisqy Barra Prasetyo'},
        {'kelas': '7D', 'nama': 'Rania Ajwa Fauzan'},
        {'kelas': '7D', 'nama': 'Rayyan Ardhana Riyadi'},
        {'kelas': '7D', 'nama': 'Razka Giffary Rakhamulia'},
        {'kelas': '7D', 'nama': 'Rifky Rahman El Mustawa'},
        {'kelas': '7D', 'nama': 'Shofiyyah Zahratul Hanan'},
        {'kelas': '7D', 'nama': 'Syatya Novanda Arifah'},
    ]

    with app.app_context():
        print("Memulai proses seeding data siswa...")
        
        # Hapus data siswa lama agar tidak duplikat saat seeding ulang
        # (Pelanggaran tetap aman karena tabel terpisah)
        try:
            num_deleted = db.session.query(Student).delete()
            db.session.commit()
            print(f"Data siswa lama ({num_deleted} baris) telah dihapus.")
        except Exception as e:
            db.session.rollback()
            print(f"Gagal menghapus data lama: {e}")

        count_new = 0
        
        for data in students_data:
            # Normalisasi input
            nama_bersih = data['nama'].strip()
            kelas_bersih = data['kelas'].strip()
            
            # Masukkan data baru
            student = Student(nama=nama_bersih, kelas=kelas_bersih)
            db.session.add(student)
            count_new += 1
                
            if count_new % 50 == 0:
                print(f"Memproses... {count_new} data ditambahkan.")
        
        try:
            db.session.commit()
            print("-" * 30)
            print(f"Proses Selesai!")
            print(f"Total data siswa berhasil ditambahkan: {count_new}")
            print("-" * 30)
        except Exception as e:
            db.session.rollback()
            print(f"Error saat commit ke database: {e}")

if __name__ == "__main__":
    seed_students_manual()